In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
x = np.random.randint(1, 100, 200)

In [17]:
x

array([99, 50, 48, 84, 54, 39, 72, 92, 61, 79, 94, 83, 92, 56, 32, 30, 24,
       37, 45, 22, 38, 48, 40, 90, 24, 38, 44, 28, 90, 99, 34, 63, 63, 64,
       89,  7, 68, 41, 12, 49, 47, 55, 65, 78, 91, 12, 21, 35, 81,  7,  5,
       93, 38, 49, 98, 43, 78, 57, 25, 34, 22, 76, 59, 65, 21, 19, 17, 41,
       10, 61, 58, 22, 37, 83, 98,  7, 72, 60, 19, 25, 34, 64, 71, 81, 68,
       84, 42, 80, 45, 76, 79, 56, 70, 65, 88,  5, 45, 98, 51, 52, 93,  3,
       52, 81, 30, 82, 25, 34, 26, 69, 47, 53, 44, 38, 56, 54, 43, 82, 34,
       85, 72, 46, 38,  5, 84, 19, 67, 83, 78, 26, 45, 41, 29, 81, 71, 45,
       41, 36, 53, 24, 45, 90, 94, 22,  6, 73, 57, 64, 14, 11, 69, 88, 42,
       41, 99, 17, 95, 52, 62, 74, 62, 60, 62, 76, 25, 80,  8, 69,  6, 75,
       13, 78, 99, 95, 82, 28, 29, 64, 92, 64, 81, 73, 75, 96, 53, 55, 46,
       65, 36, 90, 57, 43,  5, 67, 58, 89, 82, 31, 14, 26])

In [18]:
(x - min(x)) / (max(x) - min(x))

array([1.        , 0.48958333, 0.46875   , 0.84375   , 0.53125   ,
       0.375     , 0.71875   , 0.92708333, 0.60416667, 0.79166667,
       0.94791667, 0.83333333, 0.92708333, 0.55208333, 0.30208333,
       0.28125   , 0.21875   , 0.35416667, 0.4375    , 0.19791667,
       0.36458333, 0.46875   , 0.38541667, 0.90625   , 0.21875   ,
       0.36458333, 0.42708333, 0.26041667, 0.90625   , 1.        ,
       0.32291667, 0.625     , 0.625     , 0.63541667, 0.89583333,
       0.04166667, 0.67708333, 0.39583333, 0.09375   , 0.47916667,
       0.45833333, 0.54166667, 0.64583333, 0.78125   , 0.91666667,
       0.09375   , 0.1875    , 0.33333333, 0.8125    , 0.04166667,
       0.02083333, 0.9375    , 0.36458333, 0.47916667, 0.98958333,
       0.41666667, 0.78125   , 0.5625    , 0.22916667, 0.32291667,
       0.19791667, 0.76041667, 0.58333333, 0.64583333, 0.1875    ,
       0.16666667, 0.14583333, 0.39583333, 0.07291667, 0.60416667,
       0.57291667, 0.19791667, 0.35416667, 0.83333333, 0.98958

In [19]:
((x - np.mean(x))/np.std(x)).round(2)

array([ 1.71, -0.15, -0.23,  1.14,  0.  , -0.57,  0.68,  1.44,  0.27,
        0.95,  1.52,  1.1 ,  1.44,  0.08, -0.84, -0.91, -1.14, -0.65,
       -0.34, -1.22, -0.61, -0.23, -0.53,  1.37, -1.14, -0.61, -0.38,
       -0.99,  1.37,  1.71, -0.76,  0.34,  0.34,  0.38,  1.33, -1.79,
        0.53, -0.49, -1.6 , -0.19, -0.27,  0.04,  0.42,  0.91,  1.41,
       -1.6 , -1.25, -0.72,  1.03, -1.79, -1.86,  1.48, -0.61, -0.19,
        1.67, -0.42,  0.91,  0.11, -1.1 , -0.76, -1.22,  0.84,  0.19,
        0.42, -1.25, -1.33, -1.41, -0.49, -1.67,  0.27,  0.15, -1.22,
       -0.65,  1.1 ,  1.67, -1.79,  0.68,  0.23, -1.33, -1.1 , -0.76,
        0.38,  0.65,  1.03,  0.53,  1.14, -0.46,  0.99, -0.34,  0.84,
        0.95,  0.08,  0.61,  0.42,  1.29, -1.86, -0.34,  1.67, -0.11,
       -0.08,  1.48, -1.94, -0.08,  1.03, -0.91,  1.06, -1.1 , -0.76,
       -1.06,  0.57, -0.27, -0.04, -0.38, -0.61,  0.08,  0.  , -0.42,
        1.06, -0.76,  1.18,  0.68, -0.3 , -0.61, -1.86,  1.14, -1.33,
        0.49,  1.1 ,