In [1]:
import numpy as np

In [14]:
m = np.arange(1, 21).reshape(4, 5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
deel = m[:2, :2]
deel

array([[1, 2],
       [6, 7]])

In [16]:
m[1, 1]

7

In [23]:
deel[:, :] = np.array([[0,0],[0,0]])

In [25]:
m

array([[ 0,  0,  3,  4,  5],
       [ 0,  0,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
deel

array([[0, 0],
       [0, 0]])

# Monte Carlo

In [47]:
n = 100000000
x = np.random.uniform(-1, 1, n)
y = np.random.uniform(-1, 1, n)
z = np.sqrt(x ** 2 + y ** 2)    # pythagoras

area = np.sum(z < 1) / n


: 

: 

In [46]:
pi = 4 * area
pi

3.14173984

In [ ]:
area = pi * r