In [6]:
import pandas as pd
import numpy as np
import random

In [7]:
uitkomst = [False] * 99 + [True]
random.shuffle(uitkomst)
uitkomst

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [10]:
def my_classifier(features):
    return np.full(len(features), False)

In [12]:
predicted = my_classifier(uitkomst)
predicted

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [18]:
correct = predicted == uitkomst

In [19]:
accuracy = sum(correct) / len(uitkomst) * 100
accuracy

99.0

In [20]:
import sklearn.metrics as sklm

In [21]:
conf = sklm.confusion_matrix(uitkomst, predicted)
conf

array([[99,  0],
       [ 1,  0]])

In [23]:
metrics = sklm.precision_recall_fscore_support(uitkomst, predicted)
metrics

(array([0.99, 0.  ]),
 array([1., 0.]),
 array([0.99497487, 0.        ]),
 array([99,  1]))

In [25]:
precision = metrics[0]
precision

array([0.99, 0.  ])

In [27]:
recall = metrics[1]
recall

array([1., 0.])