### Aantal stijgende overgangen en aantal dalende overgangen

In [1]:
import numpy as np

In [60]:
data = np.random.randint(1, 10, 31)
data

array([8, 7, 3, 3, 2, 1, 6, 5, 9, 5, 6, 2, 6, 7, 8, 8, 1, 8, 6, 5, 1, 1,
       4, 2, 8, 6, 9, 6, 2, 6, 6])

In [61]:
d0 = data[:-1]
d1 = data[1:]

In [62]:
d0

array([8, 7, 3, 3, 2, 1, 6, 5, 9, 5, 6, 2, 6, 7, 8, 8, 1, 8, 6, 5, 1, 1,
       4, 2, 8, 6, 9, 6, 2, 6])

In [63]:
d1

array([7, 3, 3, 2, 1, 6, 5, 9, 5, 6, 2, 6, 7, 8, 8, 1, 8, 6, 5, 1, 1, 4,
       2, 8, 6, 9, 6, 2, 6, 6])

In [64]:
stijgend = d1 > d0
gelijk = d1 == d0
dalend = d1 < d0

In [65]:
aantal_stijgend = np.sum(stijgend)
aantal_gelijk = np.sum(gelijk)
aantal_dalend = np.sum(dalend)

In [67]:
print(f'totaal aantal overgangen: {len(data)-1}')
print(f'aantal stijgend: {aantal_stijgend}')
print(f'aantal gelijk: {aantal_gelijk}')
print(f'aantal dalend: {aantal_dalend}')

totaal aantal overgangen: 30
aantal stijgend: 11
aantal gelijk: 4
aantal dalend: 15
