In [4]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
a.dtype

dtype('int64')

In [39]:
m = np.arange(1, 13).reshape((3, 4))

display(m)

display( m[1, 2] )

display( m[1:, 1:4] )

display( m[1:, [False, True, False, True]] )

display( m[1:, [1, 3]] )

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

7

array([[ 6,  7,  8],
       [10, 11, 12]])

array([[ 6,  8],
       [10, 12]])

array([[ 6,  8],
       [10, 12]])

In [42]:
np.random.shuffle(m)

In [43]:
m

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [45]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [46]:
a * a

array([1, 4, 9])

In [47]:
a.T

array([1, 2, 3])

In [50]:
a.T

array([1, 2, 3])

In [53]:
a.reshape((3,1))

array([[1],
       [2],
       [3]])

In [55]:
a.transpose()

array([1, 2, 3])

In [56]:
a

array([1, 2, 3])

In [57]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [58]:
a[..., None]

array([[1],
       [2],
       [3]])

In [59]:
a[:, None]

array([[1],
       [2],
       [3]])

In [60]:
a[None, :]

array([[1, 2, 3]])

In [61]:
a

array([1, 2, 3])

In [67]:
b = a

In [68]:
b

array([2, 3, 4])

In [70]:
a[1] = 9

In [71]:
a

array([2, 9, 4])

In [72]:
b

array([2, 9, 4])